# Generated by Django 5.1.4 on 2025-02-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=10, help_text="Time limit in minutes"
                    ),
                ),
                (
                    "marking_scheme",
                    models.CharField(
                        choices=[
                            ("1,0", "+1,0"),
                            ("5,0", "+5,0"),
                            ("4,0", "+4,0"),
                            ("1,-0.25", "+1,-0.25"),
                            ("1,-0.33", "+1,-0.33"),
                            ("4,-1", "+4,-1"),
                            ("4,-2", "+4,-2"),
                        ],
                        default="1,0",
                        max_length=10,
                    ),
                ),
                ("quiz_code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("option1", models.CharField(max_length=200)),
                ("option2", models.CharField(max_length=200)),
                ("option3", models.CharField(max_length=200)),
                ("option4", models.CharField(max_length=200)),
                (
                    "correct_option",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Option 1"),
                            (2, "Option 2"),
                            (3, "Option 3"),
                            (4, "Option 4"),
                        ]
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quiz",
                    ),
                ),
            ],
        ),
    ]
