# Generated by Django 5.1.4 on 2025-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
