# Generated by Django 5.1.4 on 2025-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quiz_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
